swisspost/gateleen

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java, gateleen-test/src/test/java/org/swisspush/gateleen/routing/StaticHeaderTest.java
setting
"staticHeaders": {
"x-server-timestamp": ""
}
removes the header
=> Add ability to remove headers in routing staticHeaders

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java
Respond for HTTP 400 when client tries to set the hook which has a destination within the hooked path.
https://jira.post.ch/browse/ISAGD-1063
=> Avoid obvious hook-loops.

gateleen-scheduler/pom.xml
Gateleen does not use JDBC at all.
=> Exclude dependency to c3p0 (a JDBC connection pool implementation).

gateleen-playground/README_playground.md
Added an explanation on how to run Gateleen Playground in cluster mode with other verticles, in order to make possible the communication using the event bus.
=> Update README_playground.md adding cluster mode tips

gateleen-hook-js/src/main/webapp/app/js/gateleen-hook.js, gateleen-hook-js/src/test/javascript/hook/gateleen-hook.test.js
Until now, js hooks could only be registered on the same server `Hook.listen('/eagle/bla')`
Hooking on other servers should be supported `Hook.listen('http://server/eagle/bla')`
=> Support hooking on other servers in javascript 

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/ResurrectingPump.java
This is an ugly hack - but I find no better solution:
Unconditional resume() the (paused) readStream for cases when the writeStream's drainHandler is not invoked.
This happens if writeStream is a HttpServerResponse and meanwhile this response is closed from the other side. This leads to a 'semi paused' socket if readStream is an incoming stream from a HttpClient, causing timeouts if the connection (within the HttpClient) is reused (as we typically have keep-alive)
See also https://github.com/eclipse/vert.x/issues/2065
=> Avoid Timouts in forwarded requests.

gateleen-core/src/main/java/org/swisspush/gateleen/core/util/HttpHeaderUtil.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/util/HttpRequestHeader.java, gateleen-core/src/test/java/org/swisspush/gateleen/core/util/HttpHeaderUtilTest.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Router.java
According to RFC 2616 section 14.10
(https://tools.ietf.org/html/rfc2616#section-14.10)
The Connection headers "MUST NOT be communicated by proxies over further
connections".
This was already implemented earlier in the request stream in gateleen.
But not for the response stream. This will implement it for this stream
now.
=> [ISAGD-4215] Dont Forward 'Connection' headers.

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
Oops. Shortly reviewed the changes again and saw that I call the utility
method twice.
=> [ISAGD-4215] DontForwardConnectionClose

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
This solves #221.
Now, when upstream server closes its connection after it sended a http-Response, then we also close the connection from our own client.
=> Bugfix react on ungraceful closed client connections

gateleen-delta/pom.xml, gateleen-delta/src/main/java/org/swisspush/gateleen/delta/DeltaHandler.java, gateleen-delta/src/test/java/org/swisspush/gateleen/delta/DeltaHandlerTest.java
...to the delta values in Redis.
This is fixed here - no "x-expire-after" means "no expire" - for the resource itself but now also for its delta value
solves #226
=> If no "x-expire-after" is given but "x-delta: auto", then DeltaHandler still added a 20-day-time-to-live

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpServerResponse.java
**This is an addendum to PR https://github.com/swisspush/gateleen/pull/222** to avoid Exceptions in Forwarder when Gateleen's LocalHttpClient is used.
_Background: Gateleen's LocalHttpClient is a shortcut 'withing Gateleen' to avoid localhost-Network-Traffic - used expecially in Gateleen's router. This 'shortcut' fakes a real HttpRequest/Response - but only a few methods of the appropriate Interfaces were implemented. We now need more methods to behave 'like it's real'_
=> React on ungraceful closed client connections by closing server connection too

gateleen-hook/README_hook.md, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HttpHook.java, gateleen-hook/src/main/resources/gateleen_hooking_schema_hook, gateleen-test/src/test/java/org/swisspush/gateleen/TestUtils.java, gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java
This prevents accidential addition of an implicit "x-expire-after: 30" (30 Seconds) and also prevents overwrite of a "x-expire-after: -1".
Solves #234
=> Issue 234: Totally remove "x-expire-after" handling in HookHandler (for hooked resources)

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HttpHook.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-hook/src/main/resources/gateleen_hooking_schema_hook, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Router.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Rule.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/RuleFactory.java
- Defined new hook property 'connectionPoolSize'
- Using default connectionPoolSize of 50 (was 5000 before)
=> [#238] Enable route hooks to set a connectionPoolSize

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpServerResponse.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/util/ExpansionDeltaUtil.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/util/ResourceCollectionException.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/util/StatusCode.java, gateleen-delta/src/main/java/org/swisspush/gateleen/delta/DeltaHandler.java
- Attach a general error handler in LocalHttpServerResponse to log such
issues
- Handle undocumented DecodeException by throwing a corresponding
ResourceCollectionException
=> 240: Add error handling for crashing delta handler

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java
Use EventBus.consumer instead of EventBus.localConsumer due to much better performance in clustered environment.
See also https://github.com/eclipse/vert.x/issues/2617 and https://gist.github.com/oli-h/e44c9e42033bd10945dc6c6afa460fcb
Solves #244
=> Use EventBus.consumer instead of EventBus.localConsumer due to much better performance in clustered environment.

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java, gateleen-hook/README_hook.md, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java, gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueClient.java, gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java
- Accept only whitelisted HTTP methods on listener registration which
namely are: GET, HEAD, PUT, POST, DELETE, OPTIONS and PATCH.
- Respond with a HTTP 400 in case a not whitelisted method got used.
- Document possible exceptions on public API.
- Drop enqueueing requests with non-processable HTTP methods and log
that attempt.
Fixes #249 .
=> [#249] Enable QueueProcessor to handle other HTTP methods

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/AbstractHttpClient.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/DummyHttpServerRequest.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/DummyHttpServerResponse.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/FastFaiHttpClientResponse.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/FastFailHttpClientRequest.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/FastFailHttpServerRequest.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/FastFailHttpServerResponse.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpClientRequest.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpServerResponse.java, gateleen-delegate/src/main/java/org/swisspush/gateleen/delegate/Delegate.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/NullForwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/StorageForwarder.java, gateleen-validation/src/test/java/org/swisspush/gateleen/validation/mocks/HttpServerRequestMock.java, pom.xml
Some implementation notes:
- Gateleen implements a few core Vertx interfaces for its "SelfClient" (i.e. `... implements Http(Server|Client)(Request|Response)`).
Those interfaces are often updated/extended from one Vertx-Version to the next one. It's always a mess to update the implementations with a bunch of "throw new UnsupportedOperationException(msg);"
Therefor we now have interfaces (`FastFailHttp....`) with default-implementations (java 8 feature). This moves a lot of boiler plate code away from the main worker classes
- Migrate some core classes from Vertx class `CaseInsensitiveHeaders` to `VertxHttpHeaders`. This is a simple 1:1 replacement and is a faster implementation (according to Vert.x Guru Julien Viet)
- Due to a changed behaviour in HttpHeader when reading a 'single value' …
=> Update to Vertx 3.6.2

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HttpHook.java, gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java, gateleen-queue/src/main/java/org/swisspush/gateleen/queue/expiry/ExpiryCheckHandler.java, gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueClient.java, gateleen-queue/src/test/java/org/swisspush/gateleen/queue/expiry/ExpiryCheckHandlerTest.java
The route hooks currently expire we we enter daylight savings time (and probably do not expire on time when we leave daylight savings time). With this PR we use DateTime (which is timezone aware) to avoid such issues. 
I also removed some not used code.
=> Discontinued to use LocalDateTime because of issues upon timezone change

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
We've a hard-to-discover bug on some of our machines where we have
gateleen in place. While trying to find the real cause we ended up at
this code, which seems to hide Throwables of any kind. This patch
(hopefully) will help to find the real cause behind our randomly occurring
problem.
Further, I cannot imagine any senseful reason why we should (nearly
silently, no stack, etc) ignore Throwables like:
NullPointerException, OutOfMemoryError, ThreadDeath, StackOverflowError,
AssertionError, IOError, ThreadDeath, ... (and more)
=> Make Forwarder let devs know when someting gets wrong

gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/RecursiveExpansionHandler.java, gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/RecursiveRootHandlerBase.java, gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/RecursiveZipHandler.java
To avoid an overflow, the delta response value should be parsed as long and not as integer.
=> #331 Parse delta response as long

gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageSender.java
Changing log to warn in failing situations instead of info
=> warning log when failing to send kafka message

gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageSender.java, gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/KafkaMessageSenderTest.java
Instead of waiting for each entry to return a.k.a forcing a sequential flow, we send all messages and let `org.apache.kafka` handle batching with the properties `batch.size` and `linger.ms` by enforcing parallel composition.
=> kafka batching

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Router.java
We occasionally see 
java.io.IOException: Stream closed
in our project and would like to track down if this is related to cleanup done within Gateleen. With this PR we introduce a dedicated logger to log cleanup related activity.
=> Added a new logger to keep track on HttpClient.close()

gateleen-core/src/main/java/org/swisspush/gateleen/core/util/StringUtils.java, gateleen-core/src/test/java/org/swisspush/gateleen/core/util/StringUtilsTest.java
As announced in the issue a simple rule to treat non string json attributes in general where necessary and totally configurable.
Contains as well some minor formatting issues.
=> #382 Invalid JSON reported in routing-rule

gateleen-core/src/main/java/org/swisspush/gateleen/core/cors/CORSHandler.java, gateleen-test/src/test/java/org/swisspush/gateleen/core/cors/CORSTest.java
In our project we also use the PATCH method for cross-domain calls.
=> access control allow method PATCH for CORS

gateleen-hook/README_hook.md, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HttpHook.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-hook/src/main/resources/gateleen_hooking_schema_hook, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Rule.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/RuleFactory.java, gateleen-routing/src/main/resources/gateleen_routing_schema_routing_rules
Currently incoming requests get queued up once the connection pool is full. There is no size limit for this queue so far. With this PR we make it configurable. The default will be "unbounded", this means that everything stays the same if not actually configured.
=> support to configure maxWaitQueueSize on routes

gateleen-core/src/main/java/org/swisspush/gateleen/core/util/HttpHeaderUtil.java, gateleen-core/src/test/java/org/swisspush/gateleen/core/util/HttpHeaderUtilTest.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
This reverts commit 8a00cbad, this is due to side effects seen: 
We have now cases where the host header doesn't match with the host in the URL (it actually carries the value "localhost"), this leads to rejection with a 503 on the receiving end (in this case an open shift platform).
=> Revert "#394 Preserve Host header value if it exists"

gateleen-core/src/main/java/org/swisspush/gateleen/core/util/HttpHeaderUtil.java, gateleen-core/src/test/java/org/swisspush/gateleen/core/util/HttpHeaderUtilTest.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java, gateleen-routing/src/test/java/org/swisspush/gateleen/routing/ForwarderTest.java
This is a reduced less invasive solution to the reverted PR https://github.com/swisspush/gateleen/pull/395
The host header will be now always overwritten with the target address as it was before except if there is an explicit Host header given in the routing rules.
=> #394 Improvement for Host header handling

gateleen-hook-js/pom.xml
This is to make the build pass again. There would be even newer versions but to use them would require a little bit more time and there are a few changes that we would like to release within this week.
=> node / npm version bumped

gateleen-core/pom.xml, gateleen-core/src/main/java/org/swisspush/gateleen/core/util/StringUtils.java, gateleen-core/src/test/java/org/swisspush/gateleen/core/util/StringUtilsTest.java, gateleen-hook-js/pom.xml, gateleen-test/pom.xml, pom.xml
This is basically a workaround for something that should be addressed in https://github.com/HubSpot/jmte. However, there has been no activity in this project for the last 7 years or so. 
Also, there is some low level byte code compilation going on in jmte, not sure if this will continue to work with future Java versions. Actually I'm also uncertain if it does with current ones, I believe we do not use this feature in gateleen, so we don't necessarily see issues (and also do not necessarily care if there are issues).
We might want to look into alternatives to jmte to get rid of the dependency and this workaround.
Note: Also contains https://github.com/swisspush/gateleen/pull/405 to hopefully get a successful build.
=> synchronize access to jmte Engine to avoid rare threading issue

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/KafkaHandlerTest.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Rule.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/RuleFactory.java, gateleen-routing/src/main/resources/gateleen_routing_schema_routing_rules, gateleen-routing/src/test/java/org/swisspush/gateleen/routing/RuleFactoryTest.java
As per title. With this PR we allow to configure the vert.x property. If not configured the default kicks in as before.
=> allow to configure the HttpClientOptions.DEFAULT_KEEP_ALIVE_TIMEOUT on routes through system property

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
We have a project where connection timeouts are totally normal because clients go on / offline regularly. With this PR we still see a warning in the log if this happens but no longer log the stacktrace.
=> No longer log stacktrace in case of connection timeouts

gateleen-core/pom.xml, gateleen-core/src/main/java/org/swisspush/gateleen/core/lock/impl/RedisBasedLock.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/lock/lua/ReleaseLockRedisCommand.java, gateleen-core/src/test/java/org/swisspush/gateleen/core/util/StringUtilsTest.java, pom.xml
The build still passed even some tests failed this ways
Failure in JUnit mode for class org.swisspush.gateleen.core.logging.RequestLoggerTest
org.testng.TestNGException: 
Failure in JUnit mode for class org.swisspush.gateleen.core.logging.RequestLoggerTest
at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:115)
at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:66)
at org.testng.TestRunner$1.run(TestRunner.java:672)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
With this PR, we discontinue to use testng, only one single test had to be rewritten.
Also, after this was done, some unit tests failed around the RedisBasedLock, hence also a related bug fix in this PR.
=> Discontinued to use testng, RedisBasedLock.acquireLock() fixed

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/DeferCloseHttpClient.java
The internal class structure of the HttpClientResponseImpl has changed in vert.x 4.2.1, with this PR we adjust accordingly 
public class HttpClientResponseImpl implements HttpClientResponse  {
private HttpEventHandler eventHandler;
=> Fixed reflection access to HttpClientResponseImpl

gateleen-core/src/main/java/org/swisspush/gateleen/core/util/HttpHeaderUtil.java, gateleen-core/src/test/java/org/swisspush/gateleen/core/util/HttpHeaderUtilTest.java
With this PR we provide means to remove all duplicated headers, so far we had special treatment for header "Content-Length" only.
=> Remove all duplicated headers

gateleen-logging/src/main/java/org/swisspush/gateleen/logging/Log4jConfigurator.java, gateleen-logging/src/main/java/org/swisspush/gateleen/logging/LogController.java
We miss some loggers in our project on the configuration view. Wit this PR we change the
boolean currentContext
flag from true -> false
---
If true returns the current Context, if false returns the Context appropriate for the caller if a more appropriate Context can be determined.
---
so we are using a ' more appropriate' context to retrieve the loggers
=> Let getLoggers() return all loggers

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
Observed a case where RedisQues doesn't get informed about forwarding issues upon dequeueing: We do not arrive here
https://github.com/swisspush/vertx-redisques/blob/develop/src/main/java/org/swisspush/redisques/RedisQues.java#L1230
I mean
log.info("RedisQues QUEUE_ERROR: Consumer failed " + uid + " queue: " + queue + " (" + reply.cause().getMessage() + ")");
for in-flight requests that are then closed by the remote end.
=> End connection when request fails

gateleen-logging/src/main/java/org/swisspush/gateleen/logging/LoggingHandler.java
In our project the requests also end up in the log file of the server (beside the "requests" log file).  This is a behavior change compared to previous version where log4j1 was in use. With this PR we go back to the original behavior, requests are logged to the "requests" log file only.
=> avoid that the requests are output into 2 logfiles

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java, gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java
This is relevant for a case where we have a listener hook of type "after"
PUT http://localhost:7013/**somehost/data/mytest**/_hooks/**listeners**/http/somehost/just-a-test
{
"methods": [
"POST", 
"PUT", 
"DELETE"
],
"destination": "/somehost/data/another-target", 
"type": "**after**"
}
and on the very same endpoint also a route hook
PUT http://localhost:7013/**somehost/data/mytest**/_hooks/**route**
{
"methods": [
"POST", 
"PUT", 
"DELETE"
],
"destination": "/somehost/data/mytestroutetarget"
}  
and there is also a static route like this
"/**somehost/data/mytest**/(.*)": {
"path": "/somehost/server/return-http-error/503"
},
With this PR the listener hook will be called in case that the request can be successfully forward with the route hook, before it wasn't called.
=> listeners of type "after" do not fire if a route hook is set on the same URL in some cases

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
Reason: Writing an error message here is confusing. Error messages imply that an exception has happened so some action is required to fix it. However during request forwarding here the exception is only a subsequent error of something that happened on either side (consumer / receiver) of the forwarding process (maybe the consumer cancelled because of a timeout or the receiver run into an exception during transmission of a large response). Whatever happened ought to be logged already in the log of the consumer and/or receiver and THAT is the message(s) that requires attention and action. The error message here is just generating a lot of noise without pointing into the direction of the real problem.
=> Changed log message from error to info

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/RuleFactory.java, gateleen-routing/src/test/java/org/swisspush/gateleen/routing/RuleFactoryTest.java
The behavior change is here:
NOW:
Assert.assertEquals(1, RuleFactory.evaluatePoolSize(4, 5)); // configured 4, 5 cluster nodes
-> results in a total of 5 connection, close to what is configured
BEFORE:
Assert.assertEquals(4, RuleFactory.evaluatePoolSize(4, 5)); // configured 4, 5 cluster nodes
-> results in a total of 20 connection, higher than configured
The idea is to protect the third party / external system when running in a cluster configuration. In cases where small connection pool sizes are configured (smaller than the number of cluster nodes) we used the originalPoolSize. This resulted in a pool size of n x originalPoolSize which is possibly more then the external system can handle / against the idea of protection. With this PR we now end up with a connection pool size of 1 (per …
=> changed the poolsize evaluation if running in a cluster, simply round up

.github/workflows/maven.yml, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/AbstractHttpClient.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpClient.java, gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/ExpansionHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java
- Add some error handling.
- Reduce amount of string comparisons where a simple int compare is sufficient.
- Remove redundant text from some log messages.
- Don't call toString() twice but re-use value.
=> Cleanup random findings

gateleen-core/src/main/java/org/swisspush/gateleen/core/lua/LuaScriptState.java
This applies some (unrelated) changes requested in https://github.com/swisspost/gateleen/pull/546 .
=> [SDCISA-13736, SDCISA-10974] Apply off-topic changes

gateleen-scheduler/src/main/java/org/swisspush/gateleen/scheduler/Scheduler.java
Fix [YAGNI](https://medium.com/swlh/yagni-and-dry-the-kiss-of-death-for-your-software-project-cfd44b0654b6#fc82) error handling in Scheduler.java
=> [SDCISA-13736, SDCISA-13746] Fix YAGNI error handling in Scheduler.java

gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/ExpansionHandler.java
- Collect body only in-memory in those cases we really use it.
Related:
- https://github.com/swisspost/gateleen/issues/417
=> [SDCISA-14715] Collect body only if needed

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpClientRequest.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
Fixes: https://github.com/swisspost/gateleen/issues/569
=> Replace Exception By Warn Log In Case Of No Connection To Close

gateleen-monitoring/src/main/java/org/swisspush/gateleen/monitoring/RedisMonitor.java
Since there are many entries when calling redis INFO which are not numbers only, we want to be able to log them
=> Do logfor non-number redis metrics

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/AbstractForwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
This case often happens in scenarios with timeouts. Which usually will end up so that the HTTP response is already sent. Then when the result finally arrives, gateleen tries to respond again. Which then leads to stacktraces being logged, where we usually do not want them. I think a warning log should suffice in this case.
=> Reduce logging of some stacks

gateleen-core/src/main/java/org/swisspush/gateleen/core/exception/GateleenExceptionFactory.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/exception/GateleenThriftyExceptionFactory.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/exception/GateleenWastefulExceptionFactory.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/exception/NoStackIllegalStateException.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpClient.java, gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpServerResponse.java, gateleen-queue/src/test/java/org/swisspush/gateleen/queue/queuing/QueueProcessorTest.java
Here an example where we see that the SAME error is reported TWICE, without adding anything helpful:
```
2024-05-27T02:15:18,228 prod houston ERROR LocalHttpServerResponse - non-proper HttpServerResponse occured
java.lang.IllegalStateException: You must set the Content-Length header to be the total size of the message body BEFORE sending any data if you are not using HTTP chunked encoding.
at org.swisspush.gateleen.core.http.LocalHttpServerResponse.write(LocalHttpServerResponse.java:221) ~[gateleen-core-2.0.2.jar:?]
at org.swisspush.gateleen.core.http.LocalHttpServerResponse.write(LocalHttpServerResponse.java:20) ~[gateleen-core-2.0.2.jar:?]
at org.swisspush.gateleen.logging.LoggingWriteStream.write(LoggingWriteStream.java:47) ~[gateleen-logging-2.0.2.jar:?]
at …
```
=> Errors should be reported ONCE

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java
Fixes #590
Related:
- #583
- [QueueStatisticsCollector takes up to 10 minutes for ONE SINGLE request](https://github.com/swisspost/vertx-redisques/issues/188)
=> Move buffer allocation to another thread

gateleen-monitoring/src/main/java/org/swisspush/gateleen/monitoring/MonitoringHandler.java, gateleen-test/src/test/java/org/swisspush/gateleen/core/monitoring/MonitoringTest.java, gateleen-test/src/test/java/org/swisspush/gateleen/hook/HookQueueingStrategiesTest.java
Refer to
https://github.com/swisspost/mod-metrics/blob/develop/src/main/java/org/swisspush/metrics/MetricsModule.java#L86-L106
The purpose of this PR is to find out we  use a Gauge instead of a Histogram for "duration" metrics and also for some queue counter in order to reduce the memory foot print. The impact will be that we only have a simple counter here
compared to
=> Avoid usage of metrics where a history is kept

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java
With this PR we use the value provided in HTTP header x-timeout when set. If not, then we default to 120s as before.
Here logs from a case where the header is not set and a timeout occurred after 30s (the 120s idle timeout set has no impact here reallly)
Line 16846: 16:02:25,344 TRACE org.swisspush.gateleen.queue.queuing.QueueProcessor                     - vert.x-eventloop-thread-1 - %1WbV 03f78f18f1277b04e28a5f672d50e03e process message: io.vertx.core.eventbus.impl.MessageImpl@5d72eb03
Line 16848: 16:02:25,344 DEBUG org.swisspush.gateleen.queue.queuing.QueueProcessor                     - vert.x-eventloop-thread-1 - %1WbV 03f78f18f1277b04e28a5f672d50e03e performing request POST /houston/preflux/executeTask/localhost/123/DOCKER_PULL
Line 16850: 16:02:25,344 DEBUG …
=> Consider x-timeout HTTP header upon queue item dequeuing

gateleen-hook/README_hook.md, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java, gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java, gateleen-test/src/test/java/org/swisspush/gateleen/hook/RouteListingTest.java
Available Endpoints
1. Search Listeners
- Endpoint: /registrations/listeners
- HTTP Method: GET
- Description: Searches for all Listeners whose destination field contains the provided query string in the q parameter.
2. Search Routes
- Endpoint: /registrations/routes
- HTTP Method: GET
- Description: Searches for all Routes whose destination field contains the provided query string in the q parameter.
Query Parameter
Both endpoints support the q query parameter, which is used to filter the search results.
- q: A string to search for within the destination field of Listeners or Routes.
Example Request:
GET /registrations/listeners?q=myDestination
GET /registrations/routes?q=myDestination
Response Structure
Example Response - Searching for Listeners:
```
{
"listeners": [
"listener1", …
```
=> Issue311 improve hook searching

gateleen-expansion/README_expansion.md, gateleen-expansion/pom.xml, gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/ExpansionHandler.java, gateleen-expansion/src/test/java/org/swisspush/gateleen/expansion/ExpansionHandlerTest.java, gateleen-hook/README_hook.md, gateleen-hook/pom.xml, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java, gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java, gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueClient.java, gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java, gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueuingHandler.java, gateleen-queue/src/test/java/org/swisspush/gateleen/queue/queuing/QueueClientTest.java, gateleen-routing/README_routing.md, gateleen-routing/pom.xml, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/AbstractForwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/NullForwarder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Router.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/RouterBuilder.java, gateleen-routing/src/main/java/org/swisspush/gateleen/routing/StorageForwarder.java, gateleen-routing/src/test/java/org/swisspush/gateleen/routing/RouterTest.java, gateleen-scheduler/src/main/java/org/swisspush/gateleen/scheduler/Scheduler.java, gateleen-scheduler/src/main/java/org/swisspush/gateleen/scheduler/SchedulerFactory.java, gateleen-scheduler/src/main/java/org/swisspush/gateleen/scheduler/SchedulerResourceManager.java, pom.xml
The MonitoringHandler class uses JMX/EventBus to publish metrics. Since we don't want to use JMX anymore, I made the MonitoringHandler class optional, so it does not have to be provided.
On the other side, I added the metrics directly to the gateleen modules. Monitoring with micrometer is also optional and disabled per default.
=> #615 Made MonitoringHandler optional and added the same metrics with micrometer

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
On line 316, just after creating it, the cResHandler is added as a response handler to the cReq. No need to add it again when sending the request.
At first at removed it on line 316, since we add in while sending, but that doesn't work, because in some cases the pump starts writing the request before the send method is called and if the server already answers before the send is called, we would have no response handler installed.
This happens when forwarding to /server/return-with-status-code/503
=> Bug 618 response handler in forwarder called twice per request

gateleen-monitoring/src/main/java/org/swisspush/gateleen/monitoring/EventBusMetricsPublisher.java, gateleen-monitoring/src/main/java/org/swisspush/gateleen/monitoring/MonitoringHandler.java, gateleen-monitoring/src/test/java/org/swisspush/gateleen/monitoring/MonitoringHandlerTest.java
It looks like the monitoring address currently has only a single consumer, and since the address includes a UUID, using publish will cause the clustered eventbus sent garbage message to all nodes.
I'm not entirely certain if other consumers are registered elsewhere, but from what I can see in Gateleen, there doesn’t appear to be a second consumer.
=> replaced unnecessary publish with send

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java, gateleen-queue/src/test/java/org/swisspush/gateleen/queue/queuing/QueueProcessorTest.java
io.vertx.core.json.DecodeException: Failed to decode:String value length (20054016) exceeds the maximum allowed (20000000, from StreamReadConstraints.getMaxStringLength())
at io.vertx.core.json.jackson.DatabindCodec.fromParser(DatabindCodec.java:129) ~[vertx-core-4.5.1.jar:4.5.1]
at io.vertx.core.json.jackson.DatabindCodec.fromString(DatabindCodec.java:90) ~[vertx-core-4.5.1.jar:4.5.1]
at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:1250) ~[vertx-core-4.5.1.jar:4.5.1]
at io.vertx.core.json.JsonObject.<init>(JsonObject.java:51) ~[vertx-core-4.5.1.jar:4.5.1]
=> fix unhandled exception

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueClient.java, gateleen-queue/src/test/java/org/swisspush/gateleen/queue/queuing/QueueClientTest.java
java.lang.NullPointerException: Cannot invoke "io.vertx.core.eventbus.Message.body()" because the return value of "io.vertx.core.AsyncResult.result()" is null
=> fixed Unhandled exception
