gateleen-playground/src/main/java/org/swisspush/gateleen/playground/Server.java
gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java

adapt mainServer to handle 100-Continue automatically

adapt mainServer to handle 100-Continue automatically

---

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/expiry/ExpiryCheckHandler.java
gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueClient.java
gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java

Use an internal timestamp as queue expiration reference

---

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java
pom.xml

Salu Laurent
as explained: first PullRequest for Gateleen with few small performance improvements - mainly to feel the Github workflow.

Small Java related performance improvements

---

gateleen-player/pom.xml
pom.xml

Small, non invasive change - but leads to a cleaner dependency tree in ISA (Eagle+Houston)

Update Spring from 4.1.3 to 4.1.7

---

gateleen-scheduler/src/main/java/org/swisspush/gateleen/scheduler/Scheduler.java
gateleen-scheduler/src/main/java/org/swisspush/gateleen/scheduler/SchedulerFactory.java
gateleen-scheduler/src/main/resources/gateleen_scheduler_schema_schedulers
gateleen-test/src/test/java/org/swisspush/gateleen/scheduler/SchedulerTest.java

Added property executeOnStartup

#73 Add property to executescheduler on startup

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Router.java
gateleen-test/src/test/java/org/swisspush/gateleen/AbstractTest.java

doneHandlers in Router are called every time the routing rules change

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java

https://jira.post.ch/browse/ISAGD-1635

Introduce x-timeout header for custom request-timeouts

---

gateleen-logging/src/main/java/org/swisspush/gateleen/logging/LoggingHandler.java
gateleen-logging/src/test/java/org/swisspush/gateleen/logging/LoggingHandlerTest.java
gateleen-logging/src/test/resources/testresource_logging_handler_test

Created a fix and unit test for issue #113 
Please review and publish.

Validate URL payload filter always first fix

---

build.gradle

add proxy configuration for upload repo

prepare for release on maven central

---

gateleen-hook/README_hook.md
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/queueingstrategy/QueueingStrategyFactory.java
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/queueingstrategy/ReducedPropagationQueueingStrategy.java
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/reducedpropagation/ReducedPropagationManager.java
gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java
gateleen-hook/src/test/java/org/swisspush/gateleen/hook/queueingstrategy/QueueingStrategyFactoryTest.java
gateleen-playground/src/main/resources/playground/server/pages/hooktest.html
gateleen-test/src/test/java/org/swisspush/gateleen/hook/HookQueueingStrategiesTest.java

Changed the time units from seconds to milliseconds.
Tests successfull: https://travis-ci.org/swisspush/gateleen/builds/225653363
Please merge

Reduced propagation units change

---

gateleen-expansion/README_expansion.md
gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/ExpansionHandler.java
gateleen-expansion/src/test/java/org/swisspush/gateleen/expansion/ExpansionHandlerTest.java
gateleen-playground/src/main/java/org/swisspush/gateleen/playground/Server.java
gateleen-test/src/test/java/org/swisspush/gateleen/AbstractTest.java
gateleen-test/src/test/java/org/swisspush/gateleen/expansion/ExpandParameterTest.java

Pull Request successfully built: https://travis-ci.org/swisspush/gateleen/builds/227535916

PR for issue #139

---

.gitignore
.travis.yml
gateleen-playground/src/main/java/org/swisspush/gateleen/playground/Server.java
gateleen-playground/src/main/resources/playground/server/pages/hooktest.html
gateleen-queue/src/test/java/org/swisspush/gateleen/queue/queuing/circuitbreaker/lua/QueueCircuitBreakerUnlockSamplesLuaScriptTests.java
gateleen-test/build.gradle
gateleen-test/src/test/java/org/swisspush/gateleen/hook/RouteTest.java
gateleen-test/src/test/java/org/swisspush/gateleen/hookjs/HookJsSteps.java
gateleen-test/src/test/java/org/swisspush/gateleen/hookjs/HookJsTest.java
gateleen-test/src/test/java/org/swisspush/gateleen/routing/RequestHopValidationTest.java
gateleen-test/src/test/resources/features/hook-js.feature
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- implemented cucumber / selenium integration tests for hook-js (with old version of chrome, as newer ones don't work in travis' "precise" environment)
- fixed url in playground server for hook-js
- stabilized some other integration tests
- minor code fixes

#162 integration tests for gateleen hook js

---

gateleen-core/pom.xml
gateleen-delegate/pom.xml
gateleen-delta/pom.xml
gateleen-expansion/pom.xml
gateleen-hook-js/pom.xml
gateleen-hook/pom.xml
gateleen-logging/pom.xml
gateleen-merge/pom.xml
gateleen-monitoring/pom.xml
gateleen-packing/pom.xml
gateleen-player/pom.xml
gateleen-playground/pom.xml
gateleen-qos/pom.xml
gateleen-queue/pom.xml
gateleen-routing/pom.xml
gateleen-runconfig/pom.xml
gateleen-scheduler/pom.xml
gateleen-security/pom.xml
gateleen-test/pom.xml
gateleen-user/pom.xml
gateleen-validation/pom.xml
pom.xml

should trigger a release build

snapshot version set to prepare for release (#183)

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java

This is a further change in scope of https://github.com/swisspush/gateleen/pull/180
**Background:**
Gateleen's Forwarder implicit compared ETags and decided to response with '304 not modified' and drain response body from upstream server. This reduces the amount of data to be transferred.
But it should be the Job of the upstream server to do correct Etag-handling and answer "304" and empty body accordingly. And in fact typical http servers like lighttpd or Swisspush's vertx-rest-storage already do this.
So there is in real life no need for Gateleen to do a second look on this Etag stuff.
The implementation in Gateleen in this case was problematic as it buffered the whole reponse body from the upstream server in-memory. This could lead to OOM-Exception.
Now, instead of optimizing the code, …

Remove "304 not modified" Handling in http-Forwarder

---

.gitignore
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Listener.java

Resolving issue #186
The listener hook is now directly queued in destination queue defined in x-queue

#186 Enqueue directly to destination queue

---

gateleen-queue/src/test/java/org/swisspush/gateleen/queue/queuing/circuitbreaker/impl/QueueCircuitBreakerImplTest.java
gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java

QueueCircuitBreakerImplTests enabled again
ListenerTest made more stable

Test improved

---

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java
gateleen-runconfig/src/main/java/org/swisspush/gateleen/runconfig/RunConfig.java
gateleen-test/src/test/java/org/swisspush/gateleen/TestUtils.java
gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java
pom.xml

- update to vertx-rest-storage 2.5.2 which has config-option to answer "200 OK" when DELETE a non-existing resource
- adapt to new Config-APU of vertx-rest-storage
- remove the unconditional "x-translate-status-4xx: 200"
see #211 for details. solves #211

Issue #211: Remove "x-translate-status-4xx: 200" in HookHandler

---

gateleen-core/pom.xml
gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HeaderFunctions.java
gateleen-core/src/test/java/org/swisspush/gateleen/core/http/HeaderFunctionsTest.java
gateleen-delegate/pom.xml
gateleen-delta/pom.xml
gateleen-expansion/pom.xml
gateleen-hook-js/pom.xml
gateleen-hook/pom.xml
gateleen-hook/src/main/resources/gateleen_hooking_schema_hook
gateleen-logging/pom.xml
gateleen-merge/pom.xml
gateleen-monitoring/pom.xml
gateleen-packing/pom.xml
gateleen-player/pom.xml
gateleen-playground/pom.xml
gateleen-qos/pom.xml
gateleen-queue/pom.xml
gateleen-routing/pom.xml
gateleen-routing/src/main/resources/gateleen_routing_schema_routing_rules
gateleen-runconfig/pom.xml
gateleen-scheduler/pom.xml
gateleen-security/pom.xml
gateleen-test/pom.xml
gateleen-testhelper/pom.xml
gateleen-user/pom.xml
gateleen-validation/pom.xml
pom.xml

PR for new Release

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java

I.e. when there 'really is' a body to be send
Solves #218

Send "transfer-encoding: chunked" on outgoing requests only when needed

---

gateleen-core/src/main/java/org/swisspush/gateleen/core/storage/EventBusResourceStorage.java

[#247] Log exception when receive failed eventBus messages

---

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java
pom.xml

Also updated RedisQues version to 2.5.5 as this release also addresses Timeout issues

Issue 250 keep route hook on rehooking when possible

---

README.md

[#276] Mention publicRepos Profile in Readme

---

.travis.yml

Travis dist upgrade

---

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HeaderFunctions.java
gateleen-core/src/main/java/org/swisspush/gateleen/core/resource/CopyResourceHandler.java
gateleen-core/src/main/java/org/swisspush/gateleen/core/resource/CopyTask.java
gateleen-core/src/test/java/org/swisspush/gateleen/core/resource/CopyResourceHandlerTest.java

Same as https://github.com/swisspush/gateleen/pull/201 but for the CopyResourceHandler

provides dynamic header manipulations for the CopyResourceHandler

---

gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaConfigurationParser.java
gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaHandler.java
gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/KafkaConfigurationParserTest.java
gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/KafkaHandlerTest.java
gateleen-kafka/src/test/resources/testresource_wildcard_kafka_topic_configuration

Optional property mapper for the KafkaHandler

property mapper for gateleen-kafka

---

gateleen-core/src/main/java/org/swisspush/gateleen/core/property/PropertyHandler.java
gateleen-delegate/src/main/java/org/swisspush/gateleen/delegate/DelegateHandler.java

- improved the loggers of delegates and propertyHandler

#359 Improve Logger of Delegates and PropertyHandler

---

staging.groovy

Tested this and it seems to help. Propose to make a release once merged in order to verify it once more.

Improves reliability of staging

---

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpClientFactory.java
gateleen-hook/src/main/java/org/swisspush/gateleen/hook/Route.java
gateleen-playground/src/main/java/org/swisspush/gateleen/playground/Server.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/DeferCloseHttpClient.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Router.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/RouterBuilder.java
gateleen-test/pom.xml
gateleen-test/src/test/java/org/swisspush/gateleen/routing/RuleUpdateTest.java

This is the way I found to fix the issue #386 .
Fixes #386

Bugfix eagle corrupt stream

---

gateleen-hook/README_hook.md

Update of Route-Hook readme with missing connectionPoolSize property

---

gateleen-core/src/main/java/org/swisspush/gateleen/core/util/StringUtils.java
pom.xml

Updated jmte and removed the workaround added in https://github.com/swisspush/gateleen/pull/406

updated jmte, concurrency workaround removed

---

gateleen-kafka/README_kafka.md
gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaHandler.java
gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageValidator.java
gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/KafkaHandlerTest.java
gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/KafkaMessageValidatorTest.java
gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/StreamingRequest.java
gateleen-kafka/src/test/java/org/swisspush/gateleen/kafka/StreamingResponse.java
gateleen-playground/src/main/java/org/swisspush/gateleen/playground/Server.java
gateleen-validation/src/main/java/org/swisspush/gateleen/validation/ValidationHandler.java
gateleen-validation/src/main/java/org/swisspush/gateleen/validation/ValidationUtil.java
gateleen-validation/src/main/java/org/swisspush/gateleen/validation/Validator.java
gateleen-validation/src/test/java/org/swisspush/gateleen/validation/ValidationUtilTest.java
gateleen-validation/src/test/java/org/swisspush/gateleen/validation/ValidatorTest.java

Allow direct validation of Kafka messages

#400 Extend gateleen-validation with schemaLocation

---

gateleen-cache/src/test/java/org/swisspush/gateleen/cache/storage/RedisCacheStorageTest.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/DeferCloseHttpClient.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
pom.xml

As per description there are three issues addressed in this PR

Fixed NPE in Forwarder, improved test stability, activated code in DeferCloseHttpClient

---

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/duplicate/DuplicateCheckHandler.java

fixes https://github.com/swisspush/gateleen/issues/441

DEFAULT_REDIS_ENTRY_VALUE comparison fixed

---

gateleen-hook-js/.npmrc-post
gateleen-hook-js/.npmrc-public
gateleen-hook-js/package.json
gateleen-hook-js/pom.xml
gateleen-hook-js/src/main/webapp/app/js/gateleen-hook.js
gateleen-hook-js/src/test/javascript/hook/gateleen-hook.test.js
gateleen-hook-js/src/test/karma.conf.js

As per title, we now use chrome for karma testing.

Use chrome headless instead of phantom js

---

gateleen-core/src/main/java/org/swisspush/gateleen/core/http/BufferBridge.java
gateleen-core/src/main/java/org/swisspush/gateleen/core/http/LocalHttpClientRequest.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/DeferCloseHttpClient.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java

With this PR we fix a case where a request hangs and then timeouts. I wasn't able to write an integration test for this particular test within Gateleen itself but I do have one in my project. I'm happy to provide such a test in Gateleen itself if required, let me know. It will take me some time though.

Forwarder hangs in some cases if queue is involved

---

gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaConfigurationParser.java
gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaHandler.java

Fixes https://github.com/swisspush/gateleen/issues/427, kindly consider

Fixes the InstanceAlreadyExistsException in AppInfoParser

---

gateleen-queue/src/main/java/org/swisspush/gateleen/queue/duplicate/DuplicateCheckHandler.java
pom.xml

As per title, with this PR we move to new versions

redis-client, rest-storage, redisques update

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/StorageForwarder.java

https://beaglesecurity.com/blog/vulnerability/format-string-vulnerability.html
https://nvd.nist.gov/vuln/detail/CVE-2021-44228

(SECURITY) Fix format string injection vulnerability.

---

gateleen-playground/src/main/resources/playground/server/admin/v1/routing/rules
gateleen-routing/README_routing.md
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/AbstractForwarder.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/NullForwarder.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/StorageForwarder.java
gateleen-routing/src/test/java/org/swisspush/gateleen/routing/RouterTest.java

#625 refactored forwarding metrics to use timer only

---

gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java
gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java
gateleen-test/src/test/java/org/swisspush/gateleen/hook/ListenerTest.java
gateleen-test/src/test/java/org/swisspush/gateleen/hook/RouteListingTest.java

With this PR we fix a regression introduced with the new feature "Hook Search"

Trigger Hook Search when q param is given only

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/StorageForwarder.java

where expiry headers defined in the routing rule where ignored.

Fixed a small bug in StorageForwarder metrics

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/DeferCloseHttpClient.java

Just another refactoring baby step.

SDCISA-17956: Reduce callback-hell in DeferCloseHttpClient

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Router.java

No real changes. Only refactor lambdas to method references.

SDCISA-17956: Reduce some callback-hell in router

---

gateleen-routing/src/main/java/org/swisspush/gateleen/routing/AutomaticChunkedTransfer.java
gateleen-routing/src/main/java/org/swisspush/gateleen/routing/Forwarder.java

- Refactor (class-extraction) from Forwarder.
- Increase error resilience.
- Add LOTS of documenting comments.
- Enhance logging with debug-hints.
Related:
SDCISA-9578, SDCISA-9578, SDCISA-16515, SDCISA-17118, SDCISA-17118, SDCISA-17711, SDCISA-17711, SDCISA-17956, SDCISA-17986, SDCISA-20360, SDCISA-20740, SDCISA-20755, SDCISA-20763, SDCISA-20767, SDCISA-21066, ISAGDFPD-1553, gateleen PR 683, gateleen PR 686, gateleen PR 687, houston PR 816, gateleen PR 688.

SDCISA-17956: Forwarder: Refactor / Cleanup / Resilience
